FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl python3 make g++

COPY package.json package-lock.json* ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY tsconfig.json ./
COPY src ./src

EXPOSE 3000

CMD ["npm", "run", "dev"]
